### ISSUE TITLE
[Help Wanted] fix styling inconsistent

### ISSUE THREAD

**Issue by tylim88** [zero-to-mastery/GameSenshi#11]
the x sign normally sit in the center:
![2](https://user-images.githubusercontent.com/5227509/60261517-a8acce80-990e-11e9-8ce8-62b83ac0e21f.png)

However in Card modal:
![1](https://user-images.githubusercontent.com/5227509/60261467-8c109680-990e-11e9-8421-bf921f0cdee9.png)

as you can see it is slightly lower

both are the same components

Appreciate if anyone can willing to work on this issue

**Comment by luismartinezs** [comment]
This issue happens in firefox but not in chrome

**Comment by tylim88** [comment]
hmm, my firefox and chrome have the same issue

**Comment by quangkr** [comment]
I can't get to `Settings` page to test this, but using Firefox Dev Tool, I see that the `x`/"tick" sign is absolutely positioned, so it might be the cause. Please review my PR to see if it fixes the problem.
