### ISSUE TITLE
[BUG] I can't seem to sign up to the website

### ISSUE THREAD

**Issue by luisFebro** [zero-to-mastery/GameSenshi#17]
There is an server error when I try to register.

**Comment by tylim88** [comment]
what is the error?

I tested just now, it should work fine

did you follow the steps in readme to setup?
![image](https://user-images.githubusercontent.com/5227509/63456091-ba2ed480-c480-11e9-9afa-ea7a420c8eb1.png)

**Comment by luisFebro** [comment]
I see. It happens when I try to register to the website. 

This is the screenshot of the error I got:
<img width="242" alt="gamesenshi-issue" src="https://user-images.githubusercontent.com/28769901/63463641-955c4200-c42b-11e9-8a48-fb3d28896202.png">

Ah, okay. I will advance more in the zero-to-master course and follow these steps. I am exactly learning on NPM at the moment. (=

**Comment by tylim88** [comment]
oh this is server side error, this error is due to not able to verify email

it seem like you setup your own firebase function, the email verification is third party service that need api key

since your server dont have the api key, it throw error

**Comment by luisFebro** [comment]
Thanks for the feedback!
